// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cert.proto

package java_test;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string request1 = 1;</code>
   */
  String getRequest1();
  /**
   * <code>optional string request1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequest1Bytes();

  /**
   * <code>optional string request2 = 2;</code>
   */
  String getRequest2();
  /**
   * <code>optional string request2 = 2;</code>
   */
  com.google.protobuf.ByteString
      getRequest2Bytes();
}
