// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cert.proto

package java_test;

public interface ResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Result)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string result1 = 1;</code>
   */
  String getResult1();
  /**
   * <code>optional string result1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getResult1Bytes();

  /**
   * <code>optional string result2 = 2;</code>
   */
  String getResult2();
  /**
   * <code>optional string result2 = 2;</code>
   */
  com.google.protobuf.ByteString
      getResult2Bytes();
}
