@startuml
'https://plantuml.com/class-diagram

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList
Collection <|-- AbstractList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

/'class TargetObject{
    void operation1();
    void operation2();
}
class ProxyObject{
}
class Client{
}
Client -|> ProxyObject
ProxyObject -|> TargetObject'/

@enduml